name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-24.04  # Required OS

    steps:
      - uses: actions/checkout@v4

      - name: Install Ruby
        run: |
          sudo apt update
          sudo apt install -y rbenv ruby-build
          rbenv init
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(rbenv init -)"' >> ~/.bashrc
          source ~/.bashrc
          rbenv install 3.1.4
          rbenv global 3.1.4
          ruby -v  # Verify Ruby installation

      - name: Setup Bundler
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'

      - name: Install Dependencies
        run: bundle install

      - name: Build Site
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
