name: Build and deploy GitHub Pages
on:
  push:
    branches: [ main ]  # or your default branch
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler-cache: true # This will handle caching correctly
    
    - name: Install dependencies
      run: |
        cd docs  # adjust if your Jekyll site is in a different directory
        bundle install
    
    - name: Build site
      run: |
        cd docs  # adjust if needed
        bundle exec jekyll build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # or your default branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site  # adjust if needed
